# Generated by Django 3.0.2 on 2020-02-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imageUrl',
            field=models.TextField(blank=True, null=True),
        ),
    ]
